apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  namespace: production
spec:
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
  type: LoadBalancer